export { default as AboutSection } from './AboutSection/AboutSection'
export { default as ContactSection } from './ContactSection/ContactSection'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as MainSection } from './MainSection/MainSection'
export { default as ProjectSection } from './ProjectSection/ProjectSection'
export * from './UI'
